export type { default as iGregDate } from '@interfaces/iGregDate';
export type { default as iHijriDate } from '@interfaces/iHijriDate';
export type { default as iIcons } from '@interfaces/iIcons';
export type { default as iIf } from '@interfaces/iIf';
export type { default as iItems } from '@interfaces/iItems';
export type { iBenefit } from '@interfaces/iItems';
export type { default as iLayout } from '@interfaces/iLayout';
export type { default as iLocation } from '@interfaces/iLocation';
export type { iHandleChangeLocation } from '@interfaces/iLocation';
export type { default as iQuote } from '@interfaces/iQuote';
export type { default as iSettings } from '@interfaces/iSettings';
export type { default as iSwrResponse } from '@interfaces/iSwrResponse';
